### ISSUE TITLE
Browser doesn't load pages

### ISSUE THREAD

**Issue by mattbrambilla** [elementary/browser#17] opened 2021-05-07 20:31 UTC
## What Happened
When I start the browser and enter the page url and / or the keyword, the browser does not render the content.
I tried to browse with Firefox and everything works fine.

## Expected Behavior
Web browsing

## Steps to Reproduce

1. Open the browser
2. Go to the address bar
3. Type google.com and press enter

### Logs
Something went wrong while viewing this page. To continue, please reload or visit a different page.

## Platform Information

Elementary OS 6 Beta
Gnome web 3.38.3
(please find screenshot attached)
![Screenshot from 2021-05-07 20 29 01](https://user-images.githubusercontent.com/30724389/117505194-2a41fe80-af73-11eb-82f6-5edc70c6d220.png)

**Comment by Angedestenebres** [comment] 2021-05-08 13:26
Hey :cat: 

Yeah, this is a known issue, see: https://github.com/elementary/browser/issues/15#issuecomment-830834724

**Comment by ryonakano** [comment] 2021-05-10 03:06
Closing as a duplicate of #15

**Closed by ryonakano** 2021-05-10 03:06 UTC
