### ISSUE TITLE
Application search doesnt search for documents from Home

### ISSUE THREAD

**Issue by amgschnappi** [elementary/browser#103] opened 2023-04-28 14:10 UTC
### What Happened?

I have some pdfs in my documents and download folder.
I was expecting that typing from the Application search would show them as search results. I can then click them to open it.
But they are not searched there. I need to open files, then go to documents or download folder and then open them in the default app.

### Steps to Reproduce

1. Have some pdfs in document and download folder
2. Click search near the application menu and type the name of pdf files

### Expected Behavior

Pdf files are seen in search results.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment] 2023-04-28 15:07
Thanks for your report! This feature requests has already been filed by someone else. Closing as a duplicate of https://github.com/elementary/applications-menu/issues/54

**Closed by danirabbit** 2023-04-28 15:07 UTC
