### ISSUE TITLE
Issue with the appearance of the address bar

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/browser#44] opened 2021-09-24 16:55 UTC
Appears in light and dark mode.
![Screenshot](https://user-images.githubusercontent.com/46536067/134713052-1ab7d8b1-1d1a-4139-bf98-f6aede5bd385.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/134712579-94c8b455-7fb8-4370-8b0a-6b738920c5e7.png)

 I use a up-to-date elementary OS 6.

**Comment by cassidyjames** [comment] 2021-09-24 18:21
Thanks for reporting! This is actually a duplicate of https://github.com/elementary/stylesheet/issues/1045

**Closed by cassidyjames** 2021-09-24 18:21 UTC
