### ISSUE TITLE
Incorrect tab bar position in full screen mode

### ISSUE THREAD

**Issue by kdwk** [elementary/browser#51] opened 2021-11-21 05:09 UTC
### What Happened?

https://user-images.githubusercontent.com/39268094/142750360-d377a02c-4fa1-4109-8dda-84bb5179794e.mp4

There is a gap between the tab bar and the header bar such that web content can be seen through the gap.

### Steps to Reproduce

1. Visit a website
2. Enter fullscreen mode
3. Scroll

### Expected Behavior

There is no gap between tab bar and header bar

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by mcatanzaro** [comment] 2021-11-21 15:16
It looks like the video you attached is broken? Doesn't play for me in Epiphany or Firefox.

**Comment by cassidyjames** [comment] 2021-11-22 18:35
I can confirm this on elementary OS with our stylesheet. I imagine it's actually a stylesheet issue with the new tab bar. 

![Screenshot from 2021-11-22 11-34-24](https://user-images.githubusercontent.com/611168/142916455-6fb93d9e-0cef-4783-854e-d813faf69059.png)
![Screenshot from 2021-11-22 11-34-34](https://user-images.githubusercontent.com/611168/142916464-f9ad9fb5-b07e-475b-8947-171631d4cc8f.png)

**Comment by mcatanzaro** [comment] 2021-11-22 18:50
CC: @exalm

**Comment by Exalm** [comment] 2021-11-22 18:52
I mean yes, it's something with the stylesheet. It's not reproducible with Adwaita and we definitely don't have any margins there on the ephy side.

**Comment by janxkoci** [comment] 2022-03-13 11:55
I just tried fullscreen and I see no such issue (I've finally updated to elementary OS 6.1 this week on one of my machines). The video also doesn't play for me, so I'm not sure how the issue supposed to look, but I don't see any gap with web content visible.

Can anyone still reproduce it? Else consider closing.

**Comment by Exalm** [comment] 2022-03-13 12:06
![Screenshot from 2022-03-13 16-07-25](https://user-images.githubusercontent.com/1510457/158058624-0902bff2-17ae-4a1a-a152-8759e3f23b50.png)

Can confirm. Guess it got fixed in the stylesheet at some point.

**Comment by janxkoci** [comment] 2022-03-13 12:09
@Exalm oh but that's just maximized. What about fullscreen (F11)?

**Comment by Exalm** [comment] 2022-03-13 14:11
No, that's fullscreen.

**Comment by janxkoci** [comment] 2022-03-13 14:14
Oh, sorry, I guess the black bar is some virtualization program? Sorry it confused me, I thought it was the wingpanel..

**Comment by Exalm** [comment] 2022-03-13 17:05
Yep.

**Closed** 2022-03-13 17:13 UTC
Labels: Status: Confirmed
